---
title: "Duckweed-Algae-Snail model"
author: "Shuqing Xu"
date: "2023-12-02"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load data}
setwd("C:/Users/laura/Desktop/Modelling");
#setwd("~/Documents/ShuqingXu/Students");

d <- read.csv("1_Exp2c_2d_algae_duckweed__duckweed_algae_day7_csv.csv",sep=";") 
d.snail<-read.csv("2_Exp3a,3b_snail_on_algae__snail_on_duckweed_24h_csv.csv",sep=";")

d.sp<-d[d$focal_species=="Sp",];
d.ch<-d[d$focal_species=="Ch",];

```

## Estimate a11 and a12;
Following the tutorial from https://hankstevens.github.io/Primer-of-Ecology/comp.html
Per capita effect of species 1 on its growth rate can be expressed as:
r1-2*r1*a11*N1-r1*a12*N2

```{r estimate a11 and a12}
#install.packages("xlsx")
library("xlsx")
#BiocManager::install("xlsx")
 set.seed(1)
# assume linear regression;
data.sp.sub<-d.sp[!is.na(d.sp$growth),];
data.ch.sub<-d.ch[!is.na(d.ch$growth),];
data.snail.sp<-d.snail[d.snail$focal_species=="Sp",];
data.snail.ch<-d.snail[d.snail$focal_species=="Ch",];


model.snail.ch<-lm(log(leftover)~nr_snails,data=d.snail[d.snail$focal_species=="Ch",])


model.sp<-lm(growth~day0+competitor_constant,data=data.sp.sub);
model.ch<-lm(growth~day0+competitor_constant,data=data.ch.sub);
model.snail.sp<-lm(log(leftover)~nr_snails,data=data.snail.sp);
model.snail.ch<-lm(log(leftover)~nr_snails,data=data.snail.ch);

model.sp.resid<-model.sp$residuals;
model.ch.resid<-model.ch$residuals;
model.snail.sp.resid<-model.snail.sp$residuals;
model.snail.ch.resid<-model.snail.ch$residuals;

# perform permutations;
 R<-500 # Number of Repetitions
    a11<-rep(0,R)
    r1<-rep(0,R)
    a12<-rep(0,R)
    a22<-rep(0,R)
    r2<-rep(0,R)
    a21<-rep(0,R)
    b1<-rep(0,R)
    b2<-rep(0,R)
    
  for (i in 1:R){
        growth.sp.bootstrap<-model.sp$fit+sample(model.sp.resid,replace=TRUE)
        growth.ch.bootstrap<-model.ch$fit+sample(model.ch.resid,replace=TRUE)
        snail.sp.bootstrap<-model.snail.sp$fit+sample(model.snail.sp.resid,replace=TRUE)
        snail.ch.bootstrap<-model.snail.ch$fit+sample(model.snail.ch.resid,replace=TRUE)

      # estimate parameters for Sp
      var1<-lm(growth.sp.bootstrap~data.sp.sub$day0+data.sp.sub$competitor_constant)$coef
        a11[i]<- 0-(var1[2])/(2*var1[1]);
        r1[i]<- var1[1];
        a12[i]<- 0-var1[3]/var1[1]        
        
      # estimate parameters for Ch
        
      var2<-lm(growth.ch.bootstrap~data.ch.sub$day0+data.ch.sub$competitor_constant)$coef
        a22[i]<- 0-(var2[2])/(2*var2[1]);
        r2[i]<- var2[1];
        a21[i]<- 0-var2[3]/var2[1]        

      # estimate parameters for snails herbivory on Sp
      var3<-lm(snail.sp.bootstrap~data.snail.sp$nr_snails)$coef
        b1[i]<- 0-var3[2];

      # estimate parameters for snails herbivory on Ch
      var4<-lm(snail.ch.bootstrap~data.snail.ch$nr_snails)$coef
        dim(data.snail.ch)
#        length(snail.sp.bootstrap)
        b2[i]<- 0-var4[2];
  }

prior1<-(1-a12*0.9-b1);
prior2<-(1-a12*1.3-b1);
prior3<-(1-a12*4.1-b1);
prior4<-(1-a12*5.8-b1);

prior1

#export a table for the parameters;
out.table<-matrix(nrow=14,ncol=4);
out.table[1,]<-c("r1", mean(r1), quantile(r1,c(0.025,0.975)))
out.table[2,]<-c("r2", mean(r2), quantile(r2,c(0.025,0.975)))
out.table[3,]<-c("a11", mean(a11), quantile(a11,c(0.025,0.975)))
out.table[4,]<-c("a12", mean(a12), quantile(a12,c(0.025,0.975)))
out.table[5,]<-c("a22", mean(a22), quantile(a22,c(0.025,0.975)))
out.table[6,]<-c("a21", mean(a21), quantile(a21,c(0.025,0.975)))
out.table[7,]<-c("b1", mean(b1), quantile(b1,c(0.025,0.975)))
out.table[8,]<-c("b2", mean(b2), quantile(b2,c(0.025,0.975)))
out.table[9,]<-c("b1/b2", mean(b1/b2), quantile(b1/b2,c(0.025,0.975)))
out.table[10,]<-c("a12/a22", mean(a12/a22), quantile(a12/a22,c(0.025,0.975)))
out.table[11,]<-c("Prior1", mean(prior1), quantile(prior1,c(0.025,0.975)))
out.table[12,]<-c("Prior2", mean(prior2), quantile(prior2,c(0.025,0.975)))
out.table[13,]<-c("Prior3", mean(prior3), quantile(prior3,c(0.025,0.975)))
out.table[14,]<-c("Prior4", mean(prior4), quantile(prior4,c(0.025,0.975)))
  
  
colnames(out.table)<-c("Parameter","Mean","5%","95%");
row.names(out.table)<-c("r1","r2","a11","a12","a22","a21","b1","b2","b1/b2","a12/a22","Prior1","Prior2","Prior3","Prior4")
out.table<-data.frame(out.table)
write.xlsx(out.table, file="Snail_Duckweed_Algae_Parameters.xls", sheetName = "Parameters", 
  col.names = TRUE, row.names = F, append = FALSE)

######################################
library(ggplot2)
library(ggpubr)

# Function to create prior plots
prior_plot <- function(prior) {
  mean_val <- mean(prior)
  low_quantile <- quantile(prior, probs = 0.025)
  high_quantile <- quantile(prior, probs = 0.975)
  
  data_df <- data.frame(Values = prior)
  density_values <- density(data_df$Values)
  
  if (identical(prior, prior4)) {
    # For prior4: Shade where x < 0
    neg_density_values <- density_values$x[density_values$x < 0]
    shaded_data <- data.frame(x = c(neg_density_values, 0), y = c(density_values$y[density_values$x < 0], 0))
  } else {
    # For prior1, prior2, prior3: Shade where x > 0
    pos_density_values <- density_values$x[density_values$x > 0]
    shaded_data <- data.frame(x = c(0, pos_density_values), y = c(0, density_values$y[density_values$x > 0]))
  }
  
  ggplot(data_df, aes(x = Values)) +
    geom_density(fill = "grey", color = "black") +
    labs(x = NULL, y = NULL)+
    scale_x_continuous(expand = c(0, 0), limits = c(-2, 1), breaks = seq(-2, 1, 1)) +
    geom_ribbon(data = shaded_data, aes(x = x, ymin = 0, ymax = y),
                fill = "darkgoldenrod2", alpha = 0.5) +
    geom_vline(xintercept = c(mean_val, low_quantile, high_quantile, 0),
               linetype = c("longdash", "dotted", "dotted", "solid"),
               color = c("black", "black", "black", "grey"),
               size = c(0.4, 0.2, 0.2, 0.2))+
    theme(axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
}


# Generate plots for prior1, prior2, prior3, and prior4
a <- prior_plot(prior1)
a
b <- prior_plot(prior2)
c <- prior_plot(prior3)
d <- prior_plot(prior4)

# Display the plots
a
b
c
d

# Export the plots 
multi.page <- ggarrange(a,b,c,d,
                        ncol = 4, nrow = 1)
ggsave(multi.page, filename ="prior_density.pdf" ,height=3, width=15, dpi=600)
dev.off()


```



